name: Update plots

on:
  schedule:
    - cron: "42 0 * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  plots:
    name: PPoS Dex Plots
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.3

      - name: Set up Poetry
        uses: abatilo/actions-poetry@v2.3.0
        with:
          poetry-version: 1.6.1

      - name: Install Python dependencies
        run: poetry install

      - name: Save timeseries
        run: poetry run python3 ppos_dex.py timeseries --save

      - name: Save snapshots
        run: poetry run python3 ppos_dex.py snapshot --save

      - name: Commit files
        id: commit_files
        if: always()
        run: |
          git config --local user.email "cosimo.bassi@gmail.com"
          git config --local user.name "github-actions[bot]"
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "refreshed images 🤖" -a
            echo "HAS_COMMITS=true" >> "$GITHUB_ENV"
          else
            echo "no changes - skipping "
            echo "HAS_COMMITS=false" >> "$GITHUB_ENV"
          fi

      - name: Pull
        run: |
          git pull

      - name: Push changes
        uses: ad-m/github-push-action@master
        if: env.HAS_COMMITS != false
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: images
