name: PPoS Dex Test

on:
  pull_request:

  push:
    branches: [ main ]

  release:
    types: [ published ]

permissions:
  contents: read

jobs:
  ppos-dex-test:
    name: PPoS Dex Test
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.3

      - name: Set up Poetry
        uses: abatilo/actions-poetry@v2.3.0
        with:
          poetry-version: 1.6.1

      - name: Install Python dependencies
        run: poetry install

      - name: Install AlgoKit
        run: pipx install algokit

      - name: Run LocalNet
        run: algokit localnet start

      - name: Sleep to allow the LocalNet to start
        run: |
          sleep 10
          algokit localnet status

      - name: Test
        run: poetry run pytest --verbose
